pipeline {
    agent any
    tools{
        jdk 'jdk17'
        maven 'maven3'
    }
    stages{
        stage('git-checkout') {
            steps {
                git 'https://github.com/Meher9461/springboot-app.git'
            }
        }
    }
    
        stage('code-compile') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Unit Tests') {
            steps {
                sh 'mvn test'
            }
        }

        stage('code-Build') {
            steps {
                sh 'mvn clean package'
            }
        }
    
}